[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9546a9e52aeddae21e536b3002b3a731bf725cff"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "28f3fda1251ab10d9748d0009a11b5de83d2dc4c766c0a8c63d3b509ce043cae"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.3+0/legate_jl_wrapper.v25.10.3.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6461881c984ce88a8376ed35b124a7015ad14d1"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "0a7cc3e0aa4fdb2df472e042b84a8f6409714fe85db3f227382c23250bccdc97"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.3+0/legate_jl_wrapper.v25.10.3.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.11.1.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6d20985f70e73b84b26a0245fe9ddb50480f057"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "86a224bcaaf49f2825eb6fd686c1f6d0d25dec2ec451f7ec7c45d948aa857dd6"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.3+0/legate_jl_wrapper.v25.10.3.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fdbe61a302445f1ce91e7efaa4f6c43bf941efc"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "cb5003736a3b3ca2d0706454eb99d359e2e0f3abd62d79c4a67b836a2ef7a83b"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.3+0/legate_jl_wrapper.v25.10.3.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.11.1.tar.gz"
