[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce74cbbd1a4dff20185f51661362dd8b98f0510f"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "5600fb7eab1e656e0ac645f73d97bebcac79b3c8bae3bcdcba7935b30b3c23a4"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a138009511e3d5dc9498ad652396ea06d25c75e4"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "e919a5b0da4dc2142165f652f292633b2ba83169a13b4c6715b5f18961f39916"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.11.1.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c0068d004faf68ba5a29d385fa9381add9319d3"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "30b68ea62ae7d6c98012b89b52c0614db388c62ff899de02ca3a7465ac16a950"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.2-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3462f2118a9a42ce3331ecd17c8fab44f6a6c3e"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "98ce699e864c8e79a79b697fb211697e8e5b6f0df607706c504daaec814efd9c"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.2-julia_version+1.11.1.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c0068d004faf68ba5a29d385fa9381add9319d3"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "30b68ea62ae7d6c98012b89b52c0614db388c62ff899de02ca3a7465ac16a950"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.3-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3462f2118a9a42ce3331ecd17c8fab44f6a6c3e"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "98ce699e864c8e79a79b697fb211697e8e5b6f0df607706c504daaec814efd9c"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.3-julia_version+1.11.1.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c0068d004faf68ba5a29d385fa9381add9319d3"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "30b68ea62ae7d6c98012b89b52c0614db388c62ff899de02ca3a7465ac16a950"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.4-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3462f2118a9a42ce3331ecd17c8fab44f6a6c3e"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "98ce699e864c8e79a79b697fb211697e8e5b6f0df607706c504daaec814efd9c"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.4-julia_version+1.11.1.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c0068d004faf68ba5a29d385fa9381add9319d3"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "30b68ea62ae7d6c98012b89b52c0614db388c62ff899de02ca3a7465ac16a950"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.5-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3462f2118a9a42ce3331ecd17c8fab44f6a6c3e"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "98ce699e864c8e79a79b697fb211697e8e5b6f0df607706c504daaec814efd9c"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.5-julia_version+1.11.1.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c0068d004faf68ba5a29d385fa9381add9319d3"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "30b68ea62ae7d6c98012b89b52c0614db388c62ff899de02ca3a7465ac16a950"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.6-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3462f2118a9a42ce3331ecd17c8fab44f6a6c3e"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "98ce699e864c8e79a79b697fb211697e8e5b6f0df607706c504daaec814efd9c"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.6-julia_version+1.11.1.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c0068d004faf68ba5a29d385fa9381add9319d3"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "30b68ea62ae7d6c98012b89b52c0614db388c62ff899de02ca3a7465ac16a950"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.8-julia_version+1.10.0.tar.gz"
[[legate_jl_wrapper]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3462f2118a9a42ce3331ecd17c8fab44f6a6c3e"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[legate_jl_wrapper.download]]
    sha256 = "98ce699e864c8e79a79b697fb211697e8e5b6f0df607706c504daaec814efd9c"
    url = "https://github.com/JuliaBinaryWrappers/legate_jl_wrapper_jll.jl/releases/download/legate_jl_wrapper-v25.10.0+0/legate_jl_wrapper.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.8-julia_version+1.11.1.tar.gz"
