name = "legate_jl_wrapper_jll"
uuid = "6e093c14-372f-5516-b4d7-a6ce14f1038b"
version = "25.10.2+0"

[deps]
legate_jll = "e95fb1d3-fb9e-51b5-bdb8-1a812408cac9"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.10"
legate_jll = "~25.10.1"
LazyArtifacts = "< 0.0.1, 1"
libcxxwrap_julia_jll = "0.14.3"
Libdl = "< 0.0.1, 1"
TOML = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
